"""Crear indice documental y foliacion

Revision ID: 1aa68a358ccf
Revises: a3aa06c05ba8
Create Date: 2026-07-07 11:05:18.150575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa68a358ccf'
down_revision = 'a3aa06c05ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_expediente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_documento', sa.String(length=180), nullable=False),
    sa.Column('tipo_documento', sa.String(length=80), nullable=False),
    sa.Column('folio_inicio', sa.Integer(), nullable=False),
    sa.Column('folio_fin', sa.Integer(), nullable=False),
    sa.Column('total_folios', sa.Integer(), nullable=False),
    sa.Column('estado_revision', sa.String(length=80), nullable=False),
    sa.Column('es_anexo', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos_expediente')
    # ### end Alembic commands ###
