"""Crear tablas iniciales de usuarios expedientes ubicacion y bitacora

Revision ID: a3aa06c05ba8
Revises: 
Create Date: 2026-07-07 08:28:26.618202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3aa06c05ba8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('no_sp', sa.String(length=50), nullable=False),
    sa.Column('nombre_referencia', sa.String(length=150), nullable=True),
    sa.Column('estado_administrativo', sa.String(length=80), nullable=False),
    sa.Column('estado_fisico_documental', sa.String(length=80), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno'),
    sa.UniqueConstraint('no_sp')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=120), nullable=False),
    sa.Column('modulo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=80), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicaciones_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('archivador', sa.String(length=80), nullable=True),
    sa.Column('sicoin', sa.String(length=80), nullable=True),
    sa.Column('estante', sa.String(length=80), nullable=True),
    sa.Column('caja', sa.String(length=80), nullable=True),
    sa.Column('modulo', sa.String(length=80), nullable=True),
    sa.Column('posicion', sa.String(length=80), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicaciones_fisicas')
    op.drop_table('bitacora')
    op.drop_table('usuarios')
    op.drop_table('expedientes')
    # ### end Alembic commands ###
