"""Crear modulo de alertas

Revision ID: b8c884c2084a
Revises: 1aa68a358ccf
Create Date: 2026-07-07 11:55:04.861077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c884c2084a'
down_revision = '1aa68a358ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('tipo_alerta', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('gravedad', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('origen', sa.String(length=80), nullable=False),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('cerrada_por_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cerrada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_expediente.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    # ### end Alembic commands ###
