"""Crear modulo de prestamos y devoluciones

Revision ID: f6d94e964325
Revises: b8c884c2084a
Create Date: 2026-07-09 10:11:52.493895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d94e964325'
down_revision = 'b8c884c2084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestamos_expedientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('numero_control', sa.String(length=80), nullable=False),
    sa.Column('solicitante', sa.String(length=150), nullable=False),
    sa.Column('persona_entrega', sa.String(length=150), nullable=False),
    sa.Column('persona_recibe', sa.String(length=150), nullable=False),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=True),
    sa.Column('fecha_estimada_devolucion', sa.Date(), nullable=True),
    sa.Column('fecha_real_devolucion', sa.DateTime(), nullable=True),
    sa.Column('persona_devuelve', sa.String(length=150), nullable=True),
    sa.Column('persona_recibe_devolucion', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('observaciones_devolucion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_control')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos_expedientes')
    # ### end Alembic commands ###
