from app.routes.auth import auth_bp
from app.routes.dashboard import dashboard_bp
from app.routes.expedientes import expedientes_bp
from app.routes.expedientes_admin import expedientes_admin_bp
from app.routes.expediente_fisico import expediente_fisico_bp
from app.routes.verificaciones import verificaciones_bp
from app.routes.bitacora import bitacora_bp
from app.routes.indice_documental import indice_documental_bp
from app.routes.alertas import alertas_bp
from app.routes.prestamos import prestamos_bp
from app.routes.admin import admin_bp
from app.routes.integridad import integridad_bp
from app.routes.busqueda import busqueda_bp
from app.routes.cuenta import cuenta_bp
from app.routes.coordinacion import coordinacion_bp
from app.routes.coordinacion_export import coordinacion_export_bp
from app.routes.portadores import portadores_bp
from app.routes.uo import uo_bp
